# Generated by Django 5.0.4 on 2024-04-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangmanGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_to_guess', models.CharField(max_length=50)),
                ('current_state', models.CharField(max_length=50)),
                ('incorrect_guesses_made', models.PositiveIntegerField(default=0)),
                ('remaining_guesses', models.PositiveIntegerField(default=6)),
                ('game_status', models.CharField(default='InProgress', max_length=10)),
            ],
        ),
    ]
